### ISSUE TITLE
win_inet_pton cannot correctly handle unicode type of IP address

### ISSUE THREAD

**Issue by V-E-O** [Anorov/PySocks#110]
On Windows, Pysocks uses win_inet_pton.inet_pton to convert dotted IP address to bytes form, but win_inet_pton does not correctly handle unicode string.
Ref: https://github.com/hickeroar/win_inet_pton/issues/1

As:
s.connect(u"8.8.8.8", 53) actually connect to 0.0.0.8:53

This may cause a lot debugging time.
Can we convert the string explicitly in PySocks for win_inet_pton is not actively updated?
str(ip_addr) works.

Thanks!

**Comment by sethmlarson** [comment]
Has this been resolved? I released a new version of `win_inet_pton` and am currently the new maintainer.

**Comment by V-E-O** [comment]
@sethmlarson thanks, since the upstream issue resolved, it got resolved for pysocks.
