### ISSUE TITLE
luminati.io - [GeneralProxyError] Socket error: 403: Forbidden - The HTTP proxy server may not be supported by PySocks

### ISSUE THREAD

**Issue by sla-te** [Anorov/PySocks#146]
Im trying to implement https://github.com/ikvk/imap_tools/blob/master/examples/pysocks_proxy.py, which I edited to:

https://gist.github.com/chwba/0bfcf2c043a8da8fd4f8588b624a5eab

and implemented like this:

```python
from socks import HTTP
import MailBoxProxy

with MailBoxProxy(p_proxy_type=HTTP,
                  p_proxy_addr='proxy_ip',  # 1.2.3.4 or zproxy.lum-superproxy.io
                  p_proxy_port=int(proxy_port),  # 3192 or 22225
                  p_proxy_username=proxy_username,  # None or lum-customer-lum_username-zone-static-route_err-pass_dyn-ip-1.2.3.4
                  p_proxy_password=proxy_password,  # None or 'abc123'
                  p_timeout=10,
                  host='imap-host',
                  port=993 as mailbox:
    mailbox.folder.set('INBOX')
    for msg in mailbox.fetch():
        print(msg.text)
```

Tried luminati.io proxies and novaproxies.com, I get:
```
[GeneralProxyError] Socket error: 403: Forbidden
[*] Note: The HTTP proxy server may not be supported by PySocks (must be a CONNECT tunnel proxy)
```
on both providers and I am not sure what exactly is wrong.

**Comment by megz15** [comment]
did you find a solution to this? I am facing the same error with Proxiware proxies

**Comment by sla-te** [comment]
No solution and no reply sadly from the maintainers - It turns out though, that proxiware, luminati and novaproxies.com simply do not allow connections to this port. Havent found a different and working provider yet though sadly.

**Comment by 631068264** [comment]
same error when use squid

this https://www.lunaplus.net/posts/2021/06/proxy-for-smtp/  help me

**Comment by suryabca619** [comment]
Facing the same, Is any other way to send emails through proxy servers? Please mention if you guys found any. Thanks

**Comment by sla-te** [comment]
Yeah, figured out the reason is that the mailports are closed on the proxy providers side and it seems also, that its really hard to find any provider with these mailports opened.... for obvious reasons x).

That being said a more clear error message would have been better, I believe it should be possible to get more information, than just 403 forbidden.
