### ISSUE TITLE
if not set proxy , getpeername() is return None 

### ISSUE THREAD

**Issue by daoiqi** [Anorov/PySocks#18]
if not set proxy, then `getpeername()` will get None. following code
```python
sock_out = socks.socksocket(socket.AF_INET, socket.SOCK_STREAM)
ret = sock_out.connect_ex(('127.0.0.1', 3306 ))
print ret                           # 0
print sock_out.getpeername()    # None
```
in the source code:
```python
    def get_peername(self):
        """
        Returns the IP address and port number of the destination
        machine (note: get_proxy_peername returns the proxy)
        """
        return self.proxy_peername

    getpeername = get_peername

    def connect(...):
        ...
        if proxy_type is None:
            # Treat like regular socket object
            _BaseSocket.connect(self, (dest_addr, dest_port))
            return
        ...
```
in `connect()`, it just use `_BaseSocket.connect` , howere `self.proxy_peername` is None

**Comment by Anorov** [comment]
It looks like it's the documentation and arguably the naming that's at fault in this case. `get_peername()` actually returns the proxy information and `get_proxy_peername()` actually returns the destination host's information.

My 2 options are either to reverse the names, which could break existing code, or to update the documentation to indicate the correct behavior. Does anyone have any thoughts on the matter?

**Comment by Anorov** [comment]
Resolved with https://github.com/Anorov/PySocks/commit/cd6844dfc4dbe4550e30d9271d8d29cca23e3702.
