### ISSUE TITLE
Monkeypatch throws stacktrace

### ISSUE THREAD

**Issue by abrahamrhoffman** [Anorov/PySocks#19]
import socket, socks 
import urllib2

socks.set_default_proxy(socks.SOCKS5, "localhost", 44000)
socket.socket = socks.socksocket

urllib2 call
[...]
socks.GeneralProxyError: Socket error: timed out

Request is a more elegant way to handle time outs. Allowing me to skip and print something to stdout would be great! :)

**Comment by Anorov** [comment]
Does the code work properly if you don't monkeypatch?

For example:

    sock = socks.socksocket()
    sock.set_proxy(socks.SOCKS5, "localhost", 44000)
    sock.connect(("hostname.com", 80))
    sock.sendall("GET / HTTP/1.1\r\n...")
    print sock.recv(1048)

**Comment by abrahamrhoffman** [comment]
Yep, thanks! I guess monkeypatching is for monkeys :P
