### ISSUE TITLE
Why the authentication is not supported in HTTP connection? 

### ISSUE THREAD

**Issue by shubhpy** [Anorov/PySocks#23]
Lets make it supportive for HTTP authentication.

**Comment by Anorov** [comment]
HTTP proxy support is rudimentary in PySocks.

As the README states:

>Warning: PySocks/SocksiPy only supports HTTP proxies that use CONNECT tunneling. Certain HTTP proxies may not work with this library. If you wish to use HTTP proxies (and not SOCKS proxies), it is recommended that you rely on your HTTP client's native proxy support (proxies dict for requests, or urllib2.ProxyHandler for urllib2) instead.

It's much easier to handle the proxy authentication if you use urllib2, urllib3, httplib2, or requests.
