### ISSUE TITLE
Does PySocks work with SQLAlchemy

### ISSUE THREAD

**Issue by gane5h** [Anorov/PySocks#32]
I'm having to route all outgoing connections from SQLAlchemy via a proxy server. Is this the right library to accomplish this task? Thanks!

**Comment by nhywieza** [comment]
I get the same problem.
I solve it with a clumsy way.
_socket = socket.socket
socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, proxy_host, proxy_port)
socket.socket = socks.socksocket
.......

before SQLALchemy operation, I set socket.socket = _socket(the origin socket.socket)
