### ISSUE TITLE
Add LICENSE to tarball.

### ISSUE THREAD

**Issue by ralphbean** [Anorov/PySocks#43]
The license file states that:

```
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
```

... which means that, in order to be compliant with its own license, the tarball shipped to pypi needs to include the LICENSE file too.

It's easy to do!  You must add ``include LICENSE`` to a file called ``MANIFEST.in`` and it should show up in the next tarball there.

**Comment by Anorov** [comment]
Done.
