### ISSUE TITLE
Pysocks + Python 2.7 Windows Broken

### ISSUE THREAD

**Issue by mindw** [Anorov/PySocks#47]
socket.inet_ntop & socket.inet_pton are available for windows only for Python 3.4+. Almost all urllib3 tests fail when using pysocks 1.5.7 on windows (tested on win7).

caused by #35.

**Comment by Lukasa** [comment]
This is extremely unfortunate. We may have to reimplement those routines in PySocks if that's really true.

**Comment by mindw** [comment]
I used this - https://github.com/mindw/win_inet_pton/tree/unicode_tests
To pass the urllib3 tests.
