### ISSUE TITLE
Add MANIFEST (w/ LICENSE)

### ISSUE THREAD

**Issue by pmlandwehr** [Anorov/PySocks#49]
Would it be possible to get a `MANIFEST` for this package? I'm putting together a [build](https://github.com/conda-forge/staged-recipes/pull/1311#discussion_r75563157) for conda-forge, and ideally we'd like to include a link to the original license file in the build. Doing so requires a manifest with a link.

**Comment by Anorov** [comment]
Done. Sorry about that.
