### ISSUE TITLE
Use travis-ci to auto test

### ISSUE THREAD

**Issue by loggerhead** [Anorov/PySocks#55]
It's much convenient to test via a CI than manually, and it makes contribute more easier.

**Comment by lorien** [comment]
I can setup Travis tests. The problem is the test set is very small. I can write additional tests but I need sosks5 server. I can use 3proxy software. To use it I have to include it's binary in the repository. What do you think?

**Comment by loggerhead** [comment]
@lorien You can use [shadowsocks](https://github.com/shadowsocks/shadowsocks/tree/master) (a SOCKS5 proxy), and [oh](https://pypi.python.org/pypi/oh/0.1.1) (a simple TCP & UDP echo server) to do the test, them can installed through pip.

**Comment by lorien** [comment]
@loggerhead , can you provide exact ssserver command  I have to run to get socks5 proxy?

I've started `ssserver -p 9999 -k zz'
Then `curl --socks5 localhost:9999 getip.io

Nothing happens. Curl just froze.

**Comment by loggerhead** [comment]
@lorien The commands is following:

```bash
# start echo server (9000)
oh &
# start shadowsocks client (1080)
sslocal -l 1080 -k bar -m rc4-md5 -s 127.0.0.1 -p 8010 &
# start shadowsocks server (8010)
ssserver -s 127.0.0.1 -p 8010 -k bar -m rc4-md5 --forbidden-ip "" &
# test
curl --socks5 localhost:1081 127.0.0.1:9000
```

It works like the picture:

```
+------+       +---------+       +----------+        +------+
|      |       |         |       |          |        |      |
| curl +<----->+ sslocal +<----->+ ssserver +<------>+  oh  |
|      |       |         |       |          |        |      |
+------+       +---------+       +----------+        +------+
```

**Comment by lorien** [comment]
I have some progress.
Branch: https://github.com/lorien/pysocks/tree/travis
Travis build: https://travis-ci.org/lorien/PySocks/builds/193051278

I've managed to run all three kind of proxy server on python2.7: HTTPS, SOCKS4, SOCKS5
Twisted does not work well on py3k, so I think I would just run the socks4 twisted server via subprocess with python2.7 (like it already done with shadowsocks server).

**Comment by loggerhead** [comment]
That's great, notice shadowsocks __only__ support SOCKS5.

**Comment by lorien** [comment]
Yeah, it works :) https://travis-ci.org/lorien/PySocks/builds/193085111
I've not converted all tests yet, the main problem was to get proxy servers work on all python versions on travis platform.

socks4: test/socks4server.py
socks5: shadowsocks package
http(connect): test/httpproxy.py

**Comment by lorien** [comment]
Using multiple python libraries to support http/socks4/socks5 is not a stable solution. Sometimes ssserver (shadowsocks) just does not start listening on the port. Other solution (socks4 twister server) is bound to python2.7 only.
I think, more simple and stable solution is to use all-in-one proxy server 3proxy (https://github.com/z3APA3A/3proxy). It is licensed with BSD, so there would not be a problem like #57

Travis build: https://travis-ci.org/lorien/PySocks/builds/193171728
Branch: https://github.com/lorien/PySocks/tree/travis_3proxy

**Comment by lorien** [comment]
pull request: https://github.com/Anorov/PySocks/pull/63

**Comment by lorien** [comment]
@Anorov thank you for accepting the pull request. Also you need to signup account on travis-ci.org and enable PySocks repo. That would allow to run tests on each new commit and each new pull request to the PySocks repo. Right now that is not happening because only you can add main PySocks repo to travis-ci.org service.

**Comment by Anorov** [comment]
Done.

https://travis-ci.org/Anorov/PySocks
