### ISSUE TITLE
Bundled prebuilt 'test/mocks' executable violates its license

### ISSUE THREAD

**Issue by mgorny** [Anorov/PySocks#57]
The tests include a precompiled `mocks` program. However, you don't include sources for this program nor reference where it comes from. FWICS, it's https://sourceforge.net/projects/mocks -- which is GPL2. This means that by distributing the executable without the source code you are violating the license.

**Comment by Anorov** [comment]
Thanks, I was unaware. I removed it.

It's not very good for testing anyway. Hopefully I can find a pure Python SOCKS5 server.
