### ISSUE TITLE
Please Include a CHANGELOG

### ISSUE THREAD

**Issue by mcansky** [Anorov/PySocks#58]
Tracking changes that might have caused issues in software using this library would be easier with a CHANGELOG, please include one : http://keepachangelog.com/en/0.3.0/.

**Comment by Profpatsch** [comment]
Yes please. Is it safe to update to 1.6 from 1.5 or were there API changes? I just don’t know and the python type checker doesn’t particularly help, either. ;)

**Comment by Anorov** [comment]
Added.

https://github.com/Anorov/PySocks/blob/master/CHANGELOG.md

**Comment by Profpatsch** [comment]
Thanks!

**Comment by mcansky** [comment]
thanks !
