### ISSUE TITLE
Include sockshandler in pip package maybe?

### ISSUE THREAD

**Issue by ov7a** [Anorov/PySocks#6]
As you said

> `sockshandler.py` is just a "recipe"/utility for easy integration with urllib2. So, I don't think there is a need for an` __init__.py` because socks.py is the only file intended for importion.

Why not? One can use PySocks just for urllib2 (like I do). So maybe it would be a nice choice to add sockshandler in pip package?

**Comment by zed** [comment]
Here's [`sockshandler.py`'s single source compatible Python 2/3 version](https://gist.github.com/zed/08ca0adfb3b7457cb834) -- **beware**, I made changes until it worked -- no attempt to understand what the code does were made -- use with caution if at all.

**Comment by Anorov** [comment]
I've replaced sockshandler.py with your version, @zed, and have now included it in the PyPI package.

https://pypi.python.org/pypi/PySocks
