### ISSUE TITLE
How tests work?

### ISSUE THREAD

**Issue by lorien** [Anorov/PySocks#62]
Trying to understand how to run tests.
I see twisted socks4 server on 1080, tornado http server on port 8081.
I see socks5 tests send request to 1081 port? Who is listening on that port?

**Comment by vadmium** [comment]
It looks like an external program “mocks” was run on port 1081. See commit b884e93 and Issue #57.

**Comment by lorien** [comment]
Thank you, just wanted to be sure it is not the test/socks4server.py
