### ISSUE TITLE
PySocks Compatibility with Connect_EX / asyncore / asyncio

### ISSUE THREAD

**Issue by obnoxioustbh** [Anorov/PySocks#75]
The Python socket library has connect_ex which returns errors instead of raising exceptions (iirc) and asyncore, asyncio and etc all use connect_ex instead of connect which makes pysocks incompatible with these libraries. Can support be added. Thanks.

**Comment by Anorov** [comment]
I will accept any pull requests for this.

**Comment by obnoxioustbh** [comment]
Fixed some errors in OP, sorry about that.

I'd make an attempt at working on this but I feel my knowledge of things isn't where it should be to complete this. There is another issue here which more or less addresses it if someone would like to work on actual implementation https://github.com/Anorov/PySocks/issues/33

Thanks again.

**Comment by Anorov** [comment]
Let's merge into #33 then, please.
