### ISSUE TITLE
Http proxy with creds

### ISSUE THREAD

**Issue by adv-zl** [Anorov/PySocks#92]
Is it possible to use your library with http proxy with creds?
I'm trying to connect with such code
`proxy=(socks.HTTP, 'zproxy.luminati.io', 22225, 'lum-customer-zone-us_zone', 'jgnm7p3ngww1')`
But receive error: socks.GeneralProxyError: Socket error: 407: Proxy Authentication Required

**Comment by Anorov** [comment]
Please don't rely on PySocks' HTTP proxy support. I'd strongly recommend using an HTTP library with built-in support for HTTP proxies instead.
